version: "3.8"

services:
  # Your Spring Boot application
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/PrototypeDB?createDatabaseIfNotExist=true&characterEncoding=utf-8&autoReconnect=true
      SPRING_DATASOURCE_USERNAME: 'root'
      SPRING_DATASOURCE_PASSWORD: 'Valtech'
    depends_on:
      - mysql
    networks:
      - backend-network

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'Valtech' # Change this to a strong password
      MYSQL_DATABASE: 'PrototypeDB'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend-network

volumes:
  mysql_data:

networks:
  backend-network:
